services:
  springboot-app:
    image: commentservicepringboot-image1:tag1 # It is your built application image name:tag
    container_name: commentserviceappcontainer
    ports:
      - "8290:8293"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/commentservicedb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - commentservice-springmysql-network

  mysqldb:
    image: mysql:8.0 # It is image name:version taken from docker hub
    container_name: commentservicedbcontainer
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commentservicedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - commentservice-springmysql-network

networks:
  commentservice-springmysql-network:
    #driver: bridge