services:
  springboot-app:
    image: userservicespringboot-image1:tag1 # It is your built application image name:tag
    container_name: userservicespringbootapp
    ports:
      - "8290:8292"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/userservicedb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - userservice-springmysql-network

  mysqldb:
    image: mysql:8.0 # It is image name:version taken from docker hub
    container_name: userservicedbcontainer
    environment:
      DATABASE_HOST: userservice-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userservicedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - userservice-springmysql-network

networks:
  userservice-springmysql-network:
    #driver: bridge